r_gator_ackermann_controller:
  ros__parameters:
  
    type: "ackermann_steering_controller/AckermannSteeringController"
    left_front_wheel:
      steering_link_name: front_left_wheel_link
      steering_controller_name: left_steering_ctrlr
      axle_controller_name: left_front_wheel_ctrlr
      diameter: 0.59 # tire diameter

    right_front_wheel:
      steering_link_name: front_right_wheel_link
      steering_controller_name: right_steering_ctrlr
      axle_controller_name: right_front_wheel_ctrlr
      diameter: 0.59 # tire diameter

    left_rear_wheel:
      steering_link_name: rear_left_wheel_link  # Changed from link_name to steering_link_name
      axle_controller_name: left_rear_wheel_ctrlr
      diameter: 0.59

    right_rear_wheel:
      steering_link_name: rear_right_wheel_link  # Changed from link_name to steering_link_name
      axle_controller_name: right_rear_wheel_ctrlr
      diameter: 0.59
joint_state_ctrlr:
  type: joint_state_controller/JointStateController
  publish_rate: 30

left_steering_ctrlr:
  joint: left_steering_hinge_joint
  type: effort_controllers/JointPositionController
  pid: {p: 1000.0, i: 1.0, d: 5.0}

right_steering_ctrlr:
  joint: right_steering_hinge_joint
  type: effort_controllers/JointPositionController
  pid: {p: 1000.0, i: 1.0, d: 5.0}

left_front_wheel_ctrlr:
  joint: front_left_wheel_joint
  type: effort_controllers/JointVelocityController
  pid: {p: 1000.0, i: 1.0, d: 0.0, i_clamp: 5.0}

right_front_wheel_ctrlr:
  joint: front_right_wheel_joint
  type: effort_controllers/JointVelocityController
  pid: {p: 1000.0, i: 1.0, d: 0.0, i_clamp: 5.0}

left_rear_wheel_ctrlr:
  joint: rear_left_wheel_joint
  type: effort_controllers/JointVelocityController
  pid: {p: 1000.0, i: 1.0, d: 0.0, i_clamp: 5.0}

right_rear_wheel_ctrlr:
  joint: rear_right_wheel_joint
  type: effort_controllers/JointVelocityController
  pid: {p: 1000.0, i: 1.0, d: 0.0, i_clamp: 5.0}


